nelmio_api_doc:
    documentation:
        info:
            title: Siroko Cart & Checkout API
            version: 1.0.0
        servers:
            - url: http://localhost:8080
    areas:
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
        path_patterns:
            - ^/api(?!/doc)
