framework:
  rate_limiter:
    login_attempts:
      policy: 'sliding_window'
      limit: 10
      interval: '1 minute'
      cache_pool: 'cache.app'

services:
  App\Auth\Security\LoginRateLimiter:
    arguments:
      $limiter: '@limiter.login_attempts'
    tags: ['monolog.logger']
