security:
  password_hashers:
    App\Auth\Domain\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Auth\Domain\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      provider: app_user_provider
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
      custom_authenticators:
        - App\Auth\Security\JwtAuthenticator
      lazy: true
      stateless: false

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/health, roles: PUBLIC_ACCESS }
    - { path: ^/api/doc, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: ROLE_USER }
