services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: siroko_code_challenge_php
    volumes:
      - ./:/var/www/html:cached
    working_dir: '/var/www/html'
    environment:
      APP_ENV: development
      PHP_IDE_CONFIG: serverName=siroko
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable
    container_name: siroko_code_challenge_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  db:
    image: mariadb:11
    container_name: siroko_code_challenge_db
    environment:
      MARIADB_DATABASE: cart
      MARIADB_USER: cart
      MARIADB_PASSWORD: cart
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    container_name: siroko_code_challenge_redis
    ports:
        - "6379:6379"

volumes:
    mariadb_data: {}
