openapi: 3.0.0
paths:
  /health:
    get:
      tags:
        - health
      summary: 'Health check endpoint'
      operationId: 8eb974e19f6f96300df56e3bc0ee7541
      responses:
        '200':
          description: 'Service is healthy'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: ok }
                type: object
              example:
                status: ok
tags:
  -
    name: health
    description: health
