#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute


health_routes:
    resource: ../src/Health/routes.php
    type: php
    prefix: /api

auth_routes:
    resource: ../src/Auth/routes.php
    type: php
    prefix: /api

product_routes:
    resource: ../src/Product/routes.php
    type: php
    prefix: /api/products

cart_routes:
    resource: ../src/Cart/routes.php
    type: php
    prefix: /api/cart

order_routes:
    resource: ../src/Order/routes.php
    type: php

