controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


health_routes:
    resource: ../src/Health/routes.php
    type: php
    prefix: /api
